# <font color='blue'>Week 3 - Machine Learning Intro</font>
Used:
Python and its libraries; NumPy and Pandas library.
Jupyter Notebook.


Q 1. Modify the class Student by adding:

- Two more attributes 
- Two more methods
- Instantiate an object of the class
- To test the class, call methods with the object

In [2]:
class Student:
    """A class representing a student."""
    def __init__(self,n,a):
        self.full_name = n
        self.age = a
    def get_age(self):
        return self.age

#modified class

In [3]:
class Student:
    
   #initialize
    def __init__(self, nm, ag, x, ccps, bcty):
        self.full_name =nm
        self.age =ag
        self.sex =x
        self.course =ccps
        self.birth_city = bcty
        
   #Setter functions examples:     
    def setAge(self, ag):
        self.age = ag # (or) return self.age (if) def set_age(self):
    def setSex(self, x):
        self.sex = x
    def set_birth_city(self, bcty):
        self.birth_city = bcty
    
   #Getter functions examples:
    def getInfo(self):
        print("Student Name:", self.full_name, 
              "Age:", self.age,
              "Gender:", self.sex,
              "is taking the Course:", self.course,
              "BirthCity:", self.birth_city)
    def get_age(self):
        return ("My age is:", self.age)

In [4]:
try1 = Student('Nick',"555","M","Intro to Python","HK")

#I wanted to change values...#yes, you can overwrite!
try1.setAge(25) 
try1.setSex('Male')

try1.getInfo()


Student Name: Nick Age: 25 Gender: Male is taking the Course: Intro to Python BirthCity: HK


In [5]:
try1 = Student('Nick', 555, 'F', 'Intro to Python', 'JP')

#I wanted to change values...#yes, you can overwrite!
try1.setAge(25) 
try1.setSex('Male')
try1.set_birth_city('MIAMI')

try1.getInfo()
#additonal getter_method call
try1.get_age()

Student Name: Nick Age: 25 Gender: Male is taking the Course: Intro to Python BirthCity: MIAMI


('My age is:', 25)

In [6]:
#test the class
obj = Student("Nick",25,"Male","Intro to Python", "NY")
obj.getInfo()

Student Name: Nick Age: 25 Gender: Male is taking the Course: Intro to Python BirthCity: NY


Q 2. Create a class of your choice having at least three attributes and two methods. Test the class by instantiating the objects and calling the methods.

In [7]:
#new class

class Account:
    
    #initialize
    def __init__(self, nam, acNum, sn, opBal ):
        self.name = nam
        self.setAcNum(acNum)
        self.sin= sn
        self.setOpBal(opBal)
    
    #setter functions
    def setAcNum(self, acn):
         self.account_Number = '2020#1234:' + str(acn) #defauult format
    
    def setOpBal(self, op):
        self.opening_balance = 'USD: ' + str (op + 1000) + '$' # bank courtesy new customer
    
    #getter fucntions
    def getAccountInfo(self):
        print ("Ac Holder Name :", self.name,
             "\nAc number      :", self.account_Number,
             "\nSin Num        :", self.sin,
             "\nOpening Balance:", self.opening_balance  )

In [8]:
accObj1 = Account("Sumit", 5252, 587587587,40)
accObj1.getAccountInfo()

Ac Holder Name : Sumit 
Ac number      : 2020#1234:5252 
Sin Num        : 587587587 
Opening Balance: USD: 1040$


In [9]:
#test the class


Q 3. Create an Employee class. The Employee class has four instance variables and methods
- name, age, designation and salary. 
- methods (you can select methods of your choice)
- Instantiate objects and call methods to test the class

In [10]:
#new class

class Employee:
    
    def __init__(self, nam, age, title, compensa):
        self.name = nam
        self.age = age
        self.designation =title
        self.salary = compensa
        
    def setName(self, nn):
        self.name = str(nn) + ' ' + 'Patel'
    
    def setAge(self,yy):
        self.age =yy
    
    def getEmpInfo(self):
        print("Employee name: ", self.name ,  
             "\nAge: ", self.age ,
              "\nTitle: ", self.designation ,
             "\nSalary: ", self.salary     )
        

In [11]:
empObj1 = Employee("Sumit", 9, "Dev", "10k")
empObj1.getEmpInfo()

Employee name:  Sumit 
Age:  9 
Title:  Dev 
Salary:  10k


In [12]:
empObj1.setName("Mit")
empObj1.setAge(str(25) + ' yrs')

empObj1.getEmpInfo()

Employee name:  Mit Patel 
Age:  25 yrs 
Title:  Dev 
Salary:  10k


In [13]:
#test the class
%autosave 60

Autosaving every 60 seconds


**Import necessary libraries**

In [14]:
import pandas 
import numpy
import matplotlib.pyplot as matPltLibPyPlt
import seaborn as sns
%matplotlib inline

**Read the 'house-prices.csv' file**

It's not here:
https://github.com/scikit-learn/scikit-learn/blob/b194674c42d54b26137a456c510c5fdba1ba23e0/sklearn/datasets/data/boston_house_prices.csv

https://github.com/scikit-learn/scikit-learn/blob/b194674c42d54b26137a456c510c5fdba1ba23e0/sklearn/datasets/data/

It's in local folder of week-3

In [15]:
from sklearn.datasets import load_boston
myBoston = load_boston()

In [16]:
# housingCSV = pandas.read_csv('house-prices.csv')
# housingCSV

In [17]:
myBoston

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
         9.1400e+00],
        [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
         4.0300e+00],
        ...,
        [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         5.6400e+00],
        [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
         6.4800e+00],
        [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         7.8800e+00]]),
 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
        18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
        15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
        13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
        21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
        35.4, 24.7, 3

In [18]:
myBoston.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename'])

In [19]:
myBoston.data.shape

(506, 13)

In [20]:
# the target data usually known as Y

In [21]:
myBoston.target.shape

(506,)

In [22]:
myBoston.data

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
x_train, x_test, y_train, y_test = train_test_split(myBoston.data, myBoston.target, test_size = 0.3, random_state=42)

In [25]:
x_train[0]

array([2.9850e-02, 0.0000e+00, 2.1800e+00, 0.0000e+00, 4.5800e-01,
       6.4300e+00, 5.8700e+01, 6.0622e+00, 3.0000e+00, 2.2200e+02,
       1.8700e+01, 3.9412e+02, 5.2100e+00])

In [26]:
x_test[0]

array([9.1780e-02, 0.0000e+00, 4.0500e+00, 0.0000e+00, 5.1000e-01,
       6.4160e+00, 8.4100e+01, 2.6463e+00, 5.0000e+00, 2.9600e+02,
       1.6600e+01, 3.9550e+02, 9.0400e+00])

**Print few records from the dataFrame**

In [27]:
myHouseData = pandas.read_csv("house-prices.csv")
myHouseData.head(5)

Home   Price  SqFt  Bedrooms  Bathrooms  Offers Brick Neighborhood
0     1  114300  1790         2          2       2    No         East
1     2  114200  2030         4          2       3    No         East
2     3  114800  1740         3          2       1    No         East
3     4   94700  1980         3          2       3    No         East
4     5  119800  2130         3          3       3    No         East

In [28]:
myHouseData.Neighborhood.shape

(128,)

**Use area in square feet - SqFt (name this feature as X) to predict the house Price (name this feature as y).**

In [29]:
myHouseData.keys()

Index(['Home', 'Price', 'SqFt', 'Bedrooms', 'Bathrooms', 'Offers', 'Brick',
       'Neighborhood'],
      dtype='object')

In [30]:
x = myHouseData.SqFt.values


In [31]:
# x = x[ numpy.newaxis]
# print(x)
# x

In [32]:
x = x[ :, numpy.newaxis]
x
# x 

array([[1790],
       [2030],
       [1740],
       [1980],
       [2130],
       [1780],
       [1830],
       [2160],
       [2110],
       [1730],
       [2030],
       [1870],
       [1910],
       [2150],
       [2590],
       [1780],
       [2190],
       [1990],
       [1700],
       [1920],
       [1790],
       [2000],
       [1690],
       [1820],
       [2210],
       [2290],
       [2000],
       [1700],
       [1600],
       [2040],
       [2250],
       [1930],
       [2250],
       [2280],
       [2000],
       [2080],
       [1880],
       [2420],
       [1720],
       [1740],
       [1560],
       [1840],
       [1990],
       [1920],
       [1940],
       [1810],
       [1990],
       [2050],
       [1980],
       [1700],
       [2100],
       [1860],
       [2150],
       [2100],
       [1650],
       [1720],
       [2190],
       [2240],
       [1840],
       [2090],
       [2200],
       [1610],
       [2220],
       [1910],
       [1860],
       [1450],
       [22

In [33]:
y = myHouseData.Price.values
y

array([114300, 114200, 114800,  94700, 119800, 114600, 151600, 150700,
       119200, 104000, 132500, 123000, 102600, 126300, 176800, 145800,
       147100,  83600, 111400, 167200, 116200, 113800,  91700, 106100,
       156400, 149300, 137000,  99300,  69100, 188000, 182000, 112300,
       135000, 139600, 117800, 117100, 117500, 147000, 131300, 108200,
       106600, 133600, 105600, 154000, 166500, 103200, 129800,  90300,
       115900, 107500, 151100,  91100, 117400, 130800,  81300, 125700,
       140900, 152300, 138100, 155400, 180900, 100900, 161300, 120500,
       130300, 111100, 126200, 151900,  93600, 165600, 166700, 157600,
       107300, 125700, 144200, 106900, 129800, 176500, 121300, 143600,
       143400, 184300, 164800, 147700,  90500, 188300, 102700, 172500,
       127700,  97800, 143100, 116500, 142600, 157100, 160600, 152500,
       133300, 126800, 145500, 171000, 103200, 123100, 136800, 211200,
        82300, 146900, 108500, 134000, 117000, 108700, 111600, 114900,
      

**Import Linear Regression library**

In [34]:
from sklearn.linear_model import LinearRegression

## Creating and Training the Model

**Instantiate an object of the LinearRegression class**

In [35]:
myLinearModel = LinearRegression()

**Fit the model to X and y**

In [36]:
myLinearModel.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

**Print the coefficient**

In [37]:
myLinearModel.coef_

array([70.22631824])

**Print the intercept**

In [41]:
myLinearModel.intercept_

-10091.12990912312

In [42]:
myLinearModel

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

**Predict the price for a house with area 1795 Square feet**

In [48]:
ar1 = myLinearModel.predict([[1795]])
ar1

array([115965.11133686])

**Write down the linear regression equation for the built model**

In [50]:
# y = mx + c
# y = (-10091.129909123149) + 70.22631824(x)

**Predict the price for a house with area 1795 Square feet using the linear regression equation**

In [51]:
y = -10091.129909123149 + (70.22631824*1795)
y

115965.11133167685