# <font color='blue'>Week 2 - Machine Learning Intro</font>
Used:
Python and its libraries; NumPy and Pandas library.
Jupyter Notebook.

#### 1. Import the numpy package and name it as np

In [1]:
import numpy as np

**2. Create a vector/array from list [5, 5, 4, 6, 3]. Calculate mean, standard deviation and variance of the vector.**

In [2]:
myVec = np.array([5,5,4,6,3])

In [3]:
print(myVec)

[5 5 4 6 3]


In [4]:
np.mean(myVec)

4.6

In [5]:
np.std(myVec)

1.019803902718557

In [6]:
np.var(myVec)

1.04

**3. Find indices of non-zero elements from [1,2,0,0,4,0]**

In [7]:
test_01 = np.array([1,2,0,0,4,0])
print(test_01)

[1 2 0 0 4 0]


In [8]:
np.nonzero(test_01)

(array([0, 1, 4], dtype=int64),)

**4. Create an array arr of length 15, filled with 1,2,3,...,15**

In [9]:
arr = np.linspace(1,15,15)
print(arr)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]


In [10]:
arr = np.arange(1,16)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


**5. Change the shape of arr to 3 rows and 5 columns**

In [11]:
arr.shape =(3,5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


**6. Change the shape of arr to 5 rows and 3 columns**

In [12]:
arr.shape =(5,3)
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


# NOTE_SM_LAB_02

**Boolean array indexing:** Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition.

**7. Select elements from arr that are greater than 8.**

In [13]:
# o/p = array([ 9, 10, 11, 12, 13, 14, 15])

In [14]:
import numpy
arr_8plus = numpy.array(arr >8)
print(arr_8plus)

[[False False False]
 [False False False]
 [False False  True]
 [ True  True  True]
 [ True  True  True]]


In [15]:
arr_8plus_idx = (arr > 8)
print(arr_8plus_idx)

[[False False False]
 [False False False]
 [False False  True]
 [ True  True  True]
 [ True  True  True]]


In [16]:
arr[arr_8plus_idx]


array([ 9, 10, 11, 12, 13, 14, 15])

# Pandas
### Step 1. Import the pandas library and name it as pd

In [17]:
import pandas as pd

### Step 2. Import the dataset from `students.csv` and name it as students

In [18]:
student_csv= pd.read_csv('students.csv')

### Step 3. Show the first 25 entries

In [19]:
student_csv.head(25)

school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
0      GP   F   18       U     GT3       A     4     4   at_home   teacher   
1      GP   F   17       U     GT3       T     1     1   at_home     other   
2      GP   F   15       U     LE3       T     1     1   at_home     other   
3      GP   F   15       U     GT3       T     4     2    health  services   
4      GP   F   16       U     GT3       T     3     3     other     other   
5      GP   M   16       U     LE3       T     4     3  services     other   
6      GP   M   16       U     LE3       T     2     2     other     other   
7      GP   F   17       U     GT3       A     4     4     other   teacher   
8      GP   M   15       U     LE3       A     3     2  services     other   
9      GP   M   15       U     GT3       T     3     4     other     other   
10     GP   F   15       U     GT3       T     4     4   teacher    health   
11     GP   F   15       U     GT3       T     2     1  services     other   
12     GP   M   15       U     LE3       T     4     4    health  services   
13     GP   M   15       U     GT3       T     4     3   teacher     other   
14     GP   M   15       U     GT3       A     2     2     other     other   
15     GP   F   16       U     GT3       T     4     4    health     other   
16     GP   F   16       U     GT3       T     4     4  services  services   
17     GP   F   16       U     GT3       T     3     3     other     other   
18     GP   M   17       U     GT3       T     3     2  services  services   
19     GP   M   16       U     LE3       T     4     3    health     other   
20     GP   M   15       U     GT3       T     4     3   teacher     other   
21     GP   M   15       U     GT3       T     4     4    health    health   
22     GP   M   16       U     LE3       T     4     2   teacher     other   
23     GP   M   16       U     LE3       T     2     2     other     other   
24     GP   F   15       R     GT3       T     2     4  services    health   

   ... famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0  ...      4        3      4     1     1      3        6   5   6   6  
1  ...      5        3      3     1     1      3        4   5   5   6  
2  ...      4        3      2     2     3      3       10   7   8  10  
3  ...      3        2      2     1     1      5        2  15  14  15  
4  ...      4        3      2     1     2      5        4   6  10  10  
5  ...      5        4      2     1     2      5       10  15  15  15  
6  ...      4        4      4     1     1      3        0  12  12  11  
7  ...      4        1      4     1     1      1        6   6   5   6  
8  ...      4        2      2     1     1      1        0  16  18  19  
9  ...      5        5      1     1     1      5        0  14  15  15  
10 ...      3        3      3     1     2      2        0  10   8   9  
11 ...      5        2      2     1     1      4        4  10  12  12  
12 ...      4        3      3     1     3      5        2  14  14  14  
13 ...      5        4      3     1     2      3        2  10  10  11  
14 ...      4        5      2     1     1      3        0  14  16  16  
15 ...      4        4      4     1     2      2        4  14  14  14  
16 ...      3        2      3     1     2      2        6  13  14  14  
17 ...      5        3      2     1     1      4        4   8  10  10  
18 ...      5        5      5     2     4      5       16   6   5   5  
19 ...      3        1      3     1     3      5        4   8  10  10  
20 ...      4        4      1     1     1      1        0  13  14  15  
21 ...      5        4      2     1     1      5        0  12  15  15  
22 ...      4        5      1     1     3      5        2  15  15  16  
23 ...      5        4      4     2     4      5        0  13  13  12  
24 ...      4        3      2     1     1      5        2  10   9   8  

[25 rows x 33 columns]

### Step 4. Show the last 10 entries

In [20]:
student_csv.tail(10)

school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
385     MS   F   18       R     GT3       T     2     2   at_home     other   
386     MS   F   18       R     GT3       T     4     4   teacher   at_home   
387     MS   F   19       R     GT3       T     2     3  services     other   
388     MS   F   18       U     LE3       T     3     1   teacher  services   
389     MS   F   18       U     GT3       T     1     1     other     other   
390     MS   M   20       U     LE3       A     2     2  services  services   
391     MS   M   17       U     LE3       T     3     1  services  services   
392     MS   M   21       R     GT3       T     1     1     other     other   
393     MS   M   18       R     LE3       T     3     2  services     other   
394     MS   M   19       U     LE3       T     1     1     other   at_home   

    ... famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
385 ...      5        3      3     1     3      4        2  10   9  10  
386 ...      4        4      3     2     2      5        7   6   5   6  
387 ...      5        4      2     1     2      5        0   7   5   0  
388 ...      4        3      4     1     1      1        0   7   9   8  
389 ...      1        1      1     1     1      5        0   6   5   0  
390 ...      5        5      4     4     5      4       11   9   9   9  
391 ...      2        4      5     3     4      2        3  14  16  16  
392 ...      5        5      3     3     3      3        3  10   8   7  
393 ...      4        4      1     3     4      5        0  11  12  10  
394 ...      3        2      3     3     3      5        5   8   9   9  

[10 rows x 33 columns]

### Step 5. Print concise summary of the dataset using the info() method

In [21]:
student_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 33 columns):
school        395 non-null object
sex           395 non-null object
age           395 non-null int64
address       395 non-null object
famsize       395 non-null object
Pstatus       395 non-null object
Medu          395 non-null int64
Fedu          395 non-null int64
Mjob          395 non-null object
Fjob          395 non-null object
reason        395 non-null object
guardian      395 non-null object
traveltime    395 non-null int64
studytime     395 non-null int64
failures      395 non-null int64
schoolsup     395 non-null object
famsup        395 non-null object
paid          395 non-null object
activities    395 non-null object
nursery       395 non-null object
higher        395 non-null object
internet      395 non-null object
romantic      395 non-null object
famrel        395 non-null int64
freetime      395 non-null int64
goout         395 non-null int64
Dalc          395 no

### Step 6. Find number of observations in the dataset

In [22]:
student_csv.shape[0]

395

### Step 7. Find number of columns in the dataset

In [23]:
student_csv.shape[1]

33

### Step 8. Print all columns names of the dataset.

In [24]:
student_csv.head(2)

school sex  age address famsize Pstatus  Medu  Fedu     Mjob     Fjob ...  \
0     GP   F   18       U     GT3       A     4     4  at_home  teacher ...   
1     GP   F   17       U     GT3       T     1     1  at_home    other ...   

  famrel freetime  goout  Dalc  Walc health absences G1 G2 G3  
0      4        3      4     1     1      3        6  5  6  6  
1      5        3      3     1     1      3        4  5  5  6  

[2 rows x 33 columns]

In [25]:
student_csv.loc[1:0]

Empty DataFrame
Columns: [school, sex, age, address, famsize, Pstatus, Medu, Fedu, Mjob, Fjob, reason, guardian, traveltime, studytime, failures, schoolsup, famsup, paid, activities, nursery, higher, internet, romantic, famrel, freetime, goout, Dalc, Walc, health, absences, G1, G2, G3]
Index: []

[0 rows x 33 columns]

In [26]:
student_csv.columns

Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc',
       'Walc', 'health', 'absences', 'G1', 'G2', 'G3'],
      dtype='object')

### Step 9. How is the dataset indexed? 
OR 
### Print the indices of the dataset.

In [27]:
# "the index" (aka "the labels")
# O/P = RangeIndex(start=0, stop=395, step=1)
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394]


[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


In [28]:
idx0 = student_csv.index
idx1 = list(student_csv.index)
print(idx0, idx1)

RangeIndex(start=0, stop=395, step=1) [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 2

### Step 10. What is the data type of each column?

In [29]:
student_csv.info() #schema
student_csv.dtypes #data type

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 33 columns):
school        395 non-null object
sex           395 non-null object
age           395 non-null int64
address       395 non-null object
famsize       395 non-null object
Pstatus       395 non-null object
Medu          395 non-null int64
Fedu          395 non-null int64
Mjob          395 non-null object
Fjob          395 non-null object
reason        395 non-null object
guardian      395 non-null object
traveltime    395 non-null int64
studytime     395 non-null int64
failures      395 non-null int64
schoolsup     395 non-null object
famsup        395 non-null object
paid          395 non-null object
activities    395 non-null object
nursery       395 non-null object
higher        395 non-null object
internet      395 non-null object
romantic      395 non-null object
famrel        395 non-null int64
freetime      395 non-null int64
goout         395 non-null int64
Dalc          395 no

school        object
sex           object
age            int64
address       object
famsize       object
Pstatus       object
Medu           int64
Fedu           int64
Mjob          object
Fjob          object
reason        object
guardian      object
traveltime     int64
studytime      int64
failures       int64
schoolsup     object
famsup        object
paid          object
activities    object
nursery       object
higher        object
internet      object
romantic      object
famrel         int64
freetime       int64
goout          int64
Dalc           int64
Walc           int64
health         int64
absences       int64
G1             int64
G2             int64
G3             int64
dtype: object

### Step 11. Print only the `Fjob` column

In [30]:
print(student_csv.Fjob[:])

0       teacher
1         other
2         other
3      services
4         other
5         other
6         other
7       teacher
8         other
9         other
10       health
11        other
12     services
13        other
14        other
15        other
16     services
17        other
18     services
19        other
20        other
21       health
22        other
23        other
24       health
25     services
26        other
27     services
28        other
29      teacher
         ...   
365       other
366    services
367    services
368    services
369     teacher
370    services
371    services
372     at_home
373       other
374       other
375       other
376       other
377    services
378       other
379       other
380     teacher
381       other
382    services
383    services
384       other
385       other
386     at_home
387       other
388    services
389       other
390    services
391    services
392       other
393       other
394     at_home
Name: Fjob, Length: 395,

In [31]:
print(student_csv['Fjob'])

0       teacher
1         other
2         other
3      services
4         other
5         other
6         other
7       teacher
8         other
9         other
10       health
11        other
12     services
13        other
14        other
15        other
16     services
17        other
18     services
19        other
20        other
21       health
22        other
23        other
24       health
25     services
26        other
27     services
28        other
29      teacher
         ...   
365       other
366    services
367    services
368    services
369     teacher
370    services
371    services
372     at_home
373       other
374       other
375       other
376       other
377    services
378       other
379       other
380     teacher
381       other
382    services
383    services
384       other
385       other
386     at_home
387       other
388    services
389       other
390    services
391    services
392       other
393       other
394     at_home
Name: Fjob, Length: 395,

### Step 12. How many different occupations are there for `Fjob` in this dataset?

In [32]:
student_csv.Fjob.unique()

array(['teacher', 'other', 'services', 'health', 'at_home'], dtype=object)

In [33]:
len(student_csv.Fjob.unique())

5

### Step 13. What is the most frequent occupation for `Fjob`?

In [34]:
temp1 = student_csv.Fjob.describe().tail(2)
temp2 = temp1.head(1)
print(temp2)

top    other
Name: Fjob, dtype: object


In [35]:
student_csv.Fjob.value_counts()

other       217
services    111
teacher      29
at_home      20
health       18
Name: Fjob, dtype: int64

### Step 14. Generate descriptive statistics that summarize the central tendency, dispersion and shape of the dataset's distribution, excluding ``NaN`` values (Summarize the DataFrame using the method describe()). 

In [36]:
student_csv.describe() ##printing summary of the numeric column only

age        Medu        Fedu  traveltime   studytime    failures  \
count  395.000000  395.000000  395.000000  395.000000  395.000000  395.000000   
mean    16.696203    2.749367    2.521519    1.448101    2.035443    0.334177   
std      1.276043    1.094735    1.088201    0.697505    0.839240    0.743651   
min     15.000000    0.000000    0.000000    1.000000    1.000000    0.000000   
25%     16.000000    2.000000    2.000000    1.000000    1.000000    0.000000   
50%     17.000000    3.000000    2.000000    1.000000    2.000000    0.000000   
75%     18.000000    4.000000    3.000000    2.000000    2.000000    0.000000   
max     22.000000    4.000000    4.000000    4.000000    4.000000    3.000000   

           famrel    freetime       goout        Dalc        Walc      health  \
count  395.000000  395.000000  395.000000  395.000000  395.000000  395.000000   
mean     3.944304    3.235443    3.108861    1.481013    2.291139    3.554430   
std      0.896659    0.998862    1.113278    0.890741    1.287897    1.390303   
min      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000   
25%      4.000000    3.000000    2.000000    1.000000    1.000000    3.000000   
50%      4.000000    3.000000    3.000000    1.000000    2.000000    4.000000   
75%      5.000000    4.000000    4.000000    2.000000    3.000000    5.000000   
max      5.000000    5.000000    5.000000    5.000000    5.000000    5.000000   

         absences          G1          G2          G3  
count  395.000000  395.000000  395.000000  395.000000  
mean     5.708861   10.908861   10.713924   10.415190  
std      8.003096    3.319195    3.761505    4.581443  
min      0.000000    3.000000    0.000000    0.000000  
25%      0.000000    8.000000    9.000000    8.000000  
50%      4.000000   11.000000   11.000000   11.000000  
75%      8.000000   13.000000   13.000000   14.000000  
max     75.000000   19.000000   19.000000   20.000000

### Step 15. Summarize all columns of the dataset using the argument include = "all" in the method describe().

In [37]:
student_csv.describe(include='all') # all inclusive NaN

school  sex         age address famsize Pstatus        Medu  \
count     395  395  395.000000     395     395     395  395.000000   
unique      2    2         NaN       2       2       2         NaN   
top        GP    F         NaN       U     GT3       T         NaN   
freq      349  208         NaN     307     281     354         NaN   
mean      NaN  NaN   16.696203     NaN     NaN     NaN    2.749367   
std       NaN  NaN    1.276043     NaN     NaN     NaN    1.094735   
min       NaN  NaN   15.000000     NaN     NaN     NaN    0.000000   
25%       NaN  NaN   16.000000     NaN     NaN     NaN    2.000000   
50%       NaN  NaN   17.000000     NaN     NaN     NaN    3.000000   
75%       NaN  NaN   18.000000     NaN     NaN     NaN    4.000000   
max       NaN  NaN   22.000000     NaN     NaN     NaN    4.000000   

              Fedu   Mjob   Fjob     ...          famrel    freetime  \
count   395.000000    395    395     ...      395.000000  395.000000   
unique         NaN      5      5     ...             NaN         NaN   
top            NaN  other  other     ...             NaN         NaN   
freq           NaN    141    217     ...             NaN         NaN   
mean      2.521519    NaN    NaN     ...        3.944304    3.235443   
std       1.088201    NaN    NaN     ...        0.896659    0.998862   
min       0.000000    NaN    NaN     ...        1.000000    1.000000   
25%       2.000000    NaN    NaN     ...        4.000000    3.000000   
50%       2.000000    NaN    NaN     ...        4.000000    3.000000   
75%       3.000000    NaN    NaN     ...        5.000000    4.000000   
max       4.000000    NaN    NaN     ...        5.000000    5.000000   

             goout        Dalc        Walc      health    absences  \
count   395.000000  395.000000  395.000000  395.000000  395.000000   
unique         NaN         NaN         NaN         NaN         NaN   
top            NaN         NaN         NaN         NaN         NaN   
freq           NaN         NaN         NaN         NaN         NaN   
mean      3.108861    1.481013    2.291139    3.554430    5.708861   
std       1.113278    0.890741    1.287897    1.390303    8.003096   
min       1.000000    1.000000    1.000000    1.000000    0.000000   
25%       2.000000    1.000000    1.000000    3.000000    0.000000   
50%       3.000000    1.000000    2.000000    4.000000    4.000000   
75%       4.000000    2.000000    3.000000    5.000000    8.000000   
max       5.000000    5.000000    5.000000    5.000000   75.000000   

                G1          G2          G3  
count   395.000000  395.000000  395.000000  
unique         NaN         NaN         NaN  
top            NaN         NaN         NaN  
freq           NaN         NaN         NaN  
mean     10.908861   10.713924   10.415190  
std       3.319195    3.761505    4.581443  
min       3.000000    0.000000    0.000000  
25%       8.000000    9.000000    8.000000  
50%      11.000000   11.000000   11.000000  
75%      13.000000   13.000000   14.000000  
max      19.000000   19.000000   20.000000  

[11 rows x 33 columns]

### Step 16. Summarize only the `Mjob` column

In [38]:
student_csv.Mjob.describe()

count       395
unique        5
top       other
freq        141
Name: Mjob, dtype: object

### Step 17. What is the mean age of students?

In [39]:
non_round_age = student_csv.age.mean()
round_age = round(non_round_age)
print(round_age)

17


### Step 18. What are the three least occurring ages and their frequencies?

In [40]:
student_csv.age.value_counts().tail(3)

20    3
22    1
21    1
Name: age, dtype: int64

### Step 19. Sort the students by `absences` in descending order and show 15 records for the columns 'absences','Fjob','Mjob'

In [41]:
temp1 = student_csv[['absences','Fjob','Mjob']]
temp1

absences      Fjob      Mjob
0           6   teacher   at_home
1           4     other   at_home
2          10     other   at_home
3           2  services    health
4           4     other     other
5          10     other  services
6           0     other     other
7           6   teacher     other
8           0     other  services
9           0     other     other
10          0    health   teacher
11          4     other  services
12          2  services    health
13          2     other   teacher
14          0     other     other
15          4     other    health
16          6  services  services
17          4     other     other
18         16  services  services
19          4     other    health
20          0     other   teacher
21          0    health    health
22          2     other   teacher
23          0     other     other
24          2    health  services
25         14  services  services
26          2     other     other
27          4  services    health
28          4     other  services
29         16   teacher   teacher
..        ...       ...       ...
365         4     other   at_home
366         0  services   teacher
367         0  services     other
368         0  services   at_home
369        10   teacher     other
370         4  services  services
371         3  services   at_home
372         8   at_home     other
373        14     other     other
374         0     other     other
375         2     other     other
376         4     other    health
377         4  services   teacher
378         0     other     other
379        17     other   at_home
380         4   teacher   teacher
381         5     other     other
382         2  services     other
383         0  services     other
384        14     other     other
385         2     other   at_home
386         7   at_home   teacher
387         0     other  services
388         0  services   teacher
389         0     other     other
390        11  services  services
391         3  services  services
392         3     other     other
393         0     other  services
394         5   at_home     other

[395 rows x 3 columns]

In [42]:
temp2 = temp1.sort_values(['absences'],ascending=False)
temp2

absences      Fjob      Mjob
276        75  services     other
183        56     other     other
74         54  services     other
315        40     other     other
307        38  services   teacher
280        30     other  services
205        28  services   at_home
103        26     other  services
40         25     other     other
198        24   teacher  services
320        23  services  services
216        22     other     other
277        22  services   teacher
313        22     other  services
260        21     other  services
311        20     other   at_home
237        20     other     other
304        20     other     other
118        20     other     other
281        19  services   teacher
89         18    health   teacher
234        18     other     other
203        18     other     other
309        18     other   at_home
123        18     other    health
379        17     other   at_home
165        16  services  services
225        16     other     other
29         16   teacher   teacher
133        16     other  services
..        ...       ...       ...
318         0  services   at_home
154         0   teacher     other
316         0     other  services
30          0  services    health
31          0  services  services
32          0   at_home   teacher
310         0  services  services
33          0     other     other
308         0  services     other
34          0     other     other
306         0     other  services
35          0     other     other
303         0    health    health
302         0     other     other
301         0   teacher     other
124         0     other     other
298         0     other     other
296         0     other    health
194         0     other     other
43          0  services  services
291         0  services    health
160         0     other   at_home
162         0     other     other
53          0  services  services
164         0  services     other
56          0  services  services
167         0  services    health
168         0     other     other
269         0     other     other
131         0     other   at_home

[395 rows x 3 columns]

In [43]:
temp2.head(15)

absences      Fjob      Mjob
276        75  services     other
183        56     other     other
74         54  services     other
315        40     other     other
307        38  services   teacher
280        30     other  services
205        28  services   at_home
103        26     other  services
40         25     other     other
198        24   teacher  services
320        23  services  services
216        22     other     other
277        22  services   teacher
313        22     other  services
260        21     other  services

### Step 20. Select the students with `Fjob` ending at 'h'

In [44]:
t1 = student_csv.Fjob.str.endswith('h')
print(t1)

0      False
1      False
2      False
3      False
4      False
5      False
6      False
7      False
8      False
9      False
10      True
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20     False
21      True
22     False
23     False
24      True
25     False
26     False
27     False
28     False
29     False
       ...  
365    False
366    False
367    False
368    False
369    False
370    False
371    False
372    False
373    False
374    False
375    False
376    False
377    False
378    False
379    False
380    False
381    False
382    False
383    False
384    False
385    False
386    False
387    False
388    False
389    False
390    False
391    False
392    False
393    False
394    False
Name: Fjob, Length: 395, dtype: bool


In [45]:
student_csv[t1] # Boolean array indexing 

school sex  age address famsize Pstatus  Medu  Fedu      Mjob    Fjob ...  \
10      GP   F   15       U     GT3       T     4     4   teacher  health ...   
21      GP   M   15       U     GT3       T     4     4    health  health ...   
24      GP   F   15       R     GT3       T     2     4  services  health ...   
38      GP   F   15       R     GT3       T     3     4  services  health ...   
52      GP   M   15       U     LE3       A     4     2    health  health ...   
57      GP   M   15       U     GT3       T     4     4   teacher  health ...   
63      GP   F   16       U     GT3       T     4     3   teacher  health ...   
89      GP   M   16       U     LE3       A     4     4   teacher  health ...   
94      GP   M   15       U     LE3       T     2     2  services  health ...   
105     GP   F   15       U     GT3       A     3     3     other  health ...   
109     GP   F   16       U     LE3       T     4     4    health  health ...   
122     GP   F   16       U     LE3       T     2     4     other  health ...   
169     GP   F   16       U     GT3       T     4     4    health  health ...   
217     GP   M   18       U     LE3       T     3     3  services  health ...   
274     GP   F   17       U     GT3       T     2     4   at_home  health ...   
278     GP   F   18       U     GT3       T     4     4    health  health ...   
303     GP   F   17       U     GT3       T     3     2    health  health ...   
314     GP   F   19       U     GT3       T     1     1   at_home  health ...   

    famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
10       3        3      3     1     2      2        0  10   8   9  
21       5        4      2     1     1      5        0  12  15  15  
24       4        3      2     1     1      5        2  10   9   8  
38       4        3      2     1     1      5        2  12  12  11  
52       5        5      5     3     4      5        6  11  11  10  
57       3        2      2     1     1      5        4  14  15  15  
63       3        4      4     2     4      4        2  10   9   9  
89       4        1      3     3     5      5       18   8   6   7  
94       4        3      4     1     1      4        6  11  13  14  
105      4        3      3     1     1      4       10  10  11  11  
109      5        4      5     1     1      4        4  14  15  16  
122      4        2      2     1     2      5        2  13  13  13  
169      4        4      2     1     1      3        0  14  14  14  
217      3        2      4     2     4      4       13   6   6   8  
274      4        3      3     1     1      1        2  10  10  10  
278      2        4      4     1     1      4       15   9   8   8  
303      5        2      2     1     2      5        0  17  17  18  
314      4        1      2     1     1      3       14  15  13  13  

[18 rows x 33 columns]

In [46]:
### Step 21. How many `Mjob` profession names end with 'r'?

In [47]:
t1 = student_csv.Mjob.str.endswith('r')

t2 = student_csv[t1]
print(t2)

    school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  \
4       GP   F   16       U     GT3       T     3     3    other     other   
6       GP   M   16       U     LE3       T     2     2    other     other   
7       GP   F   17       U     GT3       A     4     4    other   teacher   
9       GP   M   15       U     GT3       T     3     4    other     other   
10      GP   F   15       U     GT3       T     4     4  teacher    health   
13      GP   M   15       U     GT3       T     4     3  teacher     other   
14      GP   M   15       U     GT3       A     2     2    other     other   
17      GP   F   16       U     GT3       T     3     3    other     other   
20      GP   M   15       U     GT3       T     4     3  teacher     other   
22      GP   M   16       U     LE3       T     4     2  teacher     other   
23      GP   M   16       U     LE3       T     2     2    other     other   
26      GP   M   15       U     GT3       T     2     2    other

In [48]:
t2.Mjob.value_counts()

other      141
teacher     58
Name: Mjob, dtype: int64

In [49]:
t2.Mjob.shape # total

(199,)

In [50]:
t2.Mjob.unique()

array(['other', 'teacher'], dtype=object)

In [51]:
(t2.Mjob.value_counts())

other      141
teacher     58
Name: Mjob, dtype: int64

In [52]:
len(t2.Mjob.value_counts())

2

In [53]:
len(t2.Mjob.unique())

2

### Step 22. Who is the guardian for majority of the students? mother, father or other?

In [54]:
t1 = student_csv.guardian.describe()

In [55]:
t2 = t1.tail(2)

In [56]:
t3 = t2.head(1)
print(t3)

top    mother
Name: guardian, dtype: object


In [57]:
print(t3[0])

mother


In [58]:
t3[0]

'mother'

In [59]:
t4 = student_csv.guardian.value_counts()
print(t4)

mother    273
father     90
other      32
Name: guardian, dtype: int64


In [60]:
t4.index[0]


'mother'

### Step 23. Find the number of male students

In [61]:
student_csv.sex.describe()

count     395
unique      2
top         F
freq      208
Name: sex, dtype: object

In [62]:
student_csv.sex.value_counts()

F    208
M    187
Name: sex, dtype: int64

In [63]:
t1 = student_csv.sex.value_counts()

In [64]:
t1[1]

187